/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class KalkulatorBangunRuang extends javax.swing.JFrame {
    /**
     * Creates new form KalkulatorBangunRuang
     */
    
    //Variabel Nilai-Nilai untuk Menghitung Luas dan Keliling Bangun Ruang
    double jari2L, luasL, kelilingL;
    double alasS, tinggiS, luasS, kelilingS;
    double sisiP, luasP, kelilingP;
    double panjangPP, lebarPP, luasPP, kelilingPP;
    
    public KalkulatorBangunRuang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kolomJariJariL = new javax.swing.JTextField();
        kolomLuasL = new javax.swing.JTextField();
        kolomKelilingL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kolomAlasS = new javax.swing.JTextField();
        kolomTinggiS = new javax.swing.JTextField();
        kolomLuasS = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        kolomSisiP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        kolomLuasP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        kolomKelilingP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        kolomPanjangPP = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        kolomLebarPP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        kolomLuasPP = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        kolomKelilingPP = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        kolomKelilingS = new javax.swing.JTextField();
        tombolLuasL = new javax.swing.JButton();
        tombolKelilingL = new javax.swing.JButton();
        tombolLuasS = new javax.swing.JButton();
        tombolKelilingS = new javax.swing.JButton();
        tombolLuasP = new javax.swing.JButton();
        tombolKelilingP = new javax.swing.JButton();
        tombolLuasPP = new javax.swing.JButton();
        tombolKelilingPP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Lingkaran");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Segitiga");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Persegi Panjang");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Persegi");

        jLabel5.setText("Jari-Jari");

        jLabel6.setText("Luas");

        jLabel7.setText("Keliling");

        kolomJariJariL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomJariJariLActionPerformed(evt);
            }
        });

        jLabel8.setText("Alas");

        jLabel9.setText("Tinggi");

        jLabel10.setText("Luas");

        jLabel11.setText("Sisi");

        jLabel12.setText("Luas");

        jLabel13.setText("Keliling");

        jLabel14.setText("Panjang");

        jLabel15.setText("Lebar");

        jLabel16.setText("Luas");

        jLabel17.setText("Keliling");

        jLabel18.setText("Keliling");

        tombolLuasL.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tombolLuasL.setText("Luas Lingkaran");
        tombolLuasL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLuasLActionPerformed(evt);
            }
        });

        tombolKelilingL.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tombolKelilingL.setText("Keliling Lingkaran");
        tombolKelilingL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKelilingLActionPerformed(evt);
            }
        });

        tombolLuasS.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tombolLuasS.setText("Luas Segitiga");
        tombolLuasS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLuasSActionPerformed(evt);
            }
        });

        tombolKelilingS.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tombolKelilingS.setText("Keliling Segitiga");
        tombolKelilingS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKelilingSActionPerformed(evt);
            }
        });

        tombolLuasP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tombolLuasP.setText("Luas Persegi");
        tombolLuasP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLuasPActionPerformed(evt);
            }
        });

        tombolKelilingP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tombolKelilingP.setText("Keliling Persegi");
        tombolKelilingP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKelilingPActionPerformed(evt);
            }
        });

        tombolLuasPP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tombolLuasPP.setText("Luas Persegi Panjang");
        tombolLuasPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLuasPPActionPerformed(evt);
            }
        });

        tombolKelilingPP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tombolKelilingPP.setText("Keliling Persegi Panjang");
        tombolKelilingPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKelilingPPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel5)
                        .addGap(315, 315, 315)
                        .addComponent(jLabel6)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(202, 202, 202))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kolomTinggiS, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kolomLebarPP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(kolomLuasS, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tombolLuasS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tombolLuasL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(kolomLuasL, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kolomLuasP, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tombolLuasP)
                                    .addComponent(kolomLuasPP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(kolomKelilingL, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tombolKelilingL)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(kolomKelilingP, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tombolKelilingS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(kolomKelilingS)
                                                .addComponent(tombolKelilingP, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addComponent(kolomKelilingPP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel15)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel16)
                                .addGap(227, 227, 227)
                                .addComponent(jLabel17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 217, Short.MAX_VALUE)
                                .addComponent(tombolLuasPP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tombolKelilingPP)
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel11)
                        .addGap(362, 362, 362)
                        .addComponent(jLabel12)
                        .addGap(168, 168, 168)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel8)
                        .addGap(124, 124, 124)
                        .addComponent(jLabel9)
                        .addGap(153, 153, 153)
                        .addComponent(jLabel10)))
                .addContainerGap(359, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kolomSisiP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addComponent(kolomPanjangPP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kolomJariJariL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kolomAlasS, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(481, 481, 481))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(kolomJariJariL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kolomLuasL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kolomKelilingL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolKelilingL)
                    .addComponent(tombolLuasL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kolomAlasS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kolomTinggiS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kolomLuasS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kolomKelilingS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolLuasS)
                    .addComponent(tombolKelilingS))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kolomLuasP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kolomKelilingP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(kolomSisiP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolLuasP)
                    .addComponent(tombolKelilingP))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kolomKelilingPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(kolomPanjangPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kolomLebarPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kolomLuasPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolLuasPP)
                    .addComponent(tombolKelilingPP))
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kolomJariJariLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomJariJariLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomJariJariLActionPerformed

    private void tombolLuasLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLuasLActionPerformed
        //Method Perhitungan Luas Lingkaran
        jari2L = Double.parseDouble(kolomJariJariL.getText());
        luasL = 3.14 * (jari2L*jari2L); //Rumus Luas Lingkaran
        kolomLuasL.setText(String.valueOf(luasL));
    }//GEN-LAST:event_tombolLuasLActionPerformed

    private void tombolKelilingLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKelilingLActionPerformed
        //Method Perhitungan Keliling Lingkaran
        jari2L = Double.parseDouble(kolomJariJariL.getText());
        kelilingL = 2 * (3.14*jari2L); //Rumus Keliling Lingkaran
        kolomKelilingL.setText(String.valueOf(kelilingL));
    }//GEN-LAST:event_tombolKelilingLActionPerformed

    private void tombolLuasSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLuasSActionPerformed
        //Method Perhitungan Luas Segitiga
        alasS = Double.parseDouble(kolomAlasS.getText());
        tinggiS = Double.parseDouble(kolomTinggiS.getText());
        luasS = (alasS * tinggiS) / 2; //Rumus Luas Segitiga
        kolomLuasS.setText(String.valueOf(luasS));
    }//GEN-LAST:event_tombolLuasSActionPerformed

    private void tombolKelilingSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKelilingSActionPerformed
        //Method Perhitungan Keliling Segitiga
        alasS = Double.parseDouble(kolomAlasS.getText());
        tinggiS = Double.parseDouble(kolomTinggiS.getText());
        kelilingS = alasS * alasS * alasS; //Rumus Keliling Segitiga
        kolomKelilingS.setText(String.valueOf(kelilingS));
    }//GEN-LAST:event_tombolKelilingSActionPerformed

    private void tombolLuasPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLuasPActionPerformed
        //Method Perhitungan Luas Persegi
        sisiP = Double.parseDouble(kolomSisiP.getText());
        luasP = sisiP * sisiP; //Rumus Luas Persegi
        kolomLuasP.setText(String.valueOf(luasP));
    }//GEN-LAST:event_tombolLuasPActionPerformed

    private void tombolKelilingPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKelilingPActionPerformed
        //Method Perhitungan Keliling Persegi
        sisiP = Double.parseDouble(kolomSisiP.getText());
        kelilingP = 4 * sisiP; //Rumus Keliling Persegi
        kolomKelilingP.setText(String.valueOf(kelilingP));
    }//GEN-LAST:event_tombolKelilingPActionPerformed

    private void tombolLuasPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLuasPPActionPerformed
        //Method Perhitungan Luas Persegi Panjang
        panjangPP = Double.parseDouble(kolomPanjangPP.getText());
        lebarPP = Double.parseDouble(kolomLebarPP.getText());
        luasPP = panjangPP * lebarPP; //Rumus Perhitungan Luas Persegi Panjang
        kolomLuasPP.setText(String.valueOf(luasPP));
    }//GEN-LAST:event_tombolLuasPPActionPerformed

    private void tombolKelilingPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKelilingPPActionPerformed
        //Method Perhitungan Keliling Persegi Panjang
        panjangPP = Double.parseDouble(kolomPanjangPP.getText());
        lebarPP = Double.parseDouble(kolomLebarPP.getText());
        kelilingPP = 2 * (panjangPP + lebarPP); //Rumus Keliling Persegi Panjang
        kolomKelilingPP.setText(String.valueOf(kelilingPP));
    }//GEN-LAST:event_tombolKelilingPPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorBangunRuang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kolomAlasS;
    private javax.swing.JTextField kolomJariJariL;
    private javax.swing.JTextField kolomKelilingL;
    private javax.swing.JTextField kolomKelilingP;
    private javax.swing.JTextField kolomKelilingPP;
    private javax.swing.JTextField kolomKelilingS;
    private javax.swing.JTextField kolomLebarPP;
    private javax.swing.JTextField kolomLuasL;
    private javax.swing.JTextField kolomLuasP;
    private javax.swing.JTextField kolomLuasPP;
    private javax.swing.JTextField kolomLuasS;
    private javax.swing.JTextField kolomPanjangPP;
    private javax.swing.JTextField kolomSisiP;
    private javax.swing.JTextField kolomTinggiS;
    private javax.swing.JButton tombolKelilingL;
    private javax.swing.JButton tombolKelilingP;
    private javax.swing.JButton tombolKelilingPP;
    private javax.swing.JButton tombolKelilingS;
    private javax.swing.JButton tombolLuasL;
    private javax.swing.JButton tombolLuasP;
    private javax.swing.JButton tombolLuasPP;
    private javax.swing.JButton tombolLuasS;
    // End of variables declaration//GEN-END:variables
}
